=== torstenroeder/tortilla/content/doctypes/page.dtd
<!-- TORTILLA PAGE DTD -->
<!-- version 1.3 -->

<!ELEMENT page (meta-information,content) >

    <!ELEMENT meta-information (title,author*,date,filename,translation?) >

        <!ELEMENT title       (#PCDATA) >
        <!ELEMENT author      (#PCDATA) >
        <!ELEMENT date        (#PCDATA) >
        <!ELEMENT filename    (#PCDATA) >
        <!ELEMENT translation (#PCDATA) >
        <!ATTLIST translation
            lang  (de|en)  "de"
        >

    <!ELEMENT content
        (heading|image|division
        |list|paragraph|line|get-content)*
    >
    <!ATTLIST content
        display  (all-divisions|by-divisions|selected-image)  "all-divisions"
        default  (first-division|division-list)               "first-division"
        objects  (image)                                      #IMPLIED
        class    CDATA                                        #IMPLIED
    >

        <!ELEMENT heading (#PCDATA) >
        <!ATTLIST heading
            class  CDATA  #IMPLIED
            short  CDATA  #IMPLIED
        >
        
        <!ELEMENT division
            (translation?,(heading|image|video|map|section|list|paragraph|line|get-content)*)
        >
        <!ATTLIST division
            name   CDATA  #IMPLIED
            class  CDATA  #IMPLIED
        >
        
        <!ELEMENT section
            (heading|image|video|map
            |list|paragraph|line|get-content)*
        >
        <!ATTLIST section
            name   CDATA  #IMPLIED
            class  CDATA  #IMPLIED
        >
        
        <!-- PARAGRAPHS -->

        <!ELEMENT paragraph
            (#PCDATA
            |heading|image|line|list
            |link|get-content)*
        >
        <!ATTLIST paragraph
            content  (image)  #IMPLIED
        >
        
            <!-- LINES -->

            <!ELEMENT line (#PCDATA|link)* >
            <!ATTLIST line
                content  CDATA  "text"
            >

            <!-- LINKS -->

            <!ELEMENT link (#PCDATA)* >
            <!ATTLIST link
                type  (email|site|web|file|openstreetmap)  #REQUIRED
                href       CDATA  #IMPLIED
                latitude   CDATA  #IMPLIED
                longitude  CDATA  #IMPLIED
                zoom       CDATA  #IMPLIED
            >

        <!-- LISTS -->

        <!ELEMENT list (item|get-content)* >
        <!ATTLIST list
            type  (bullets|floating-first-lines|paragraphs)  #IMPLIED
            content (keywords) #IMPLIED
        >
        
            <!ELEMENT item
                (#PCDATA
                |heading|image|line)* 
            >

        <!-- IMAGES, VIDEOS, MAPS -->

        <!ELEMENT image (#PCDATA) >
        <!ATTLIST image
            filename   CDATA  #REQUIRED
            extension  CDATA  #REQUIRED
            float    (left|right|none)  #IMPLIED
            border   (default|none)  #IMPLIED
        >

        <!ELEMENT video (#PCDATA) >
        <!ATTLIST video
            title       CDATA  #REQUIRED
            width       CDATA  #REQUIRED
            height      CDATA  #REQUIRED
            margin      CDATA  #REQUIRED
            filename    CDATA  #REQUIRED
            startimage  CDATA  #REQUIRED
        >

        <!ELEMENT map (#PCDATA) >
        <!ATTLIST map
            type        (openstreetmap)  #REQUIRED
            latitude    CDATA  #REQUIRED
            longitude   CDATA  #REQUIRED
            zoom        CDATA  #REQUIRED
            filename    CDATA  #REQUIRED
        >

        <!-- EXTERNAL CONTENT -->

        <!ELEMENT get-content EMPTY>
        <!ATTLIST get-content
            from       CDATA  #REQUIRED
            container  CDATA  #REQUIRED
            element    CDATA  #REQUIRED
            position   CDATA  #IMPLIED
        >

=== torstenroeder/tortilla/content/de/impressum.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "../doctypes/page.dtd">

<page>
    <meta-information>
        <title>Impressum</title>
        <author>Torsten Roeder</author>
        <date>November 2012</date>
        <filename>impressum.xml</filename>
        <translation lang="en">impressum</translation>
    </meta-information>
    <content display="all-divisions">
        <heading>Impressum</heading>
        <division>
            <section>
                <heading>Texte, Bilder, Technik und Layout</heading>
                <paragraph>
                    <line>Torsten Roeder</line>
                    <line>
                        <link type="web" href="http://www.torstenroeder.de/">www.torstenroeder.de</link>
                    </line>
                </paragraph>
            </section>
            <section>
                <heading>Grafiken</heading>
                <paragraph>
                    <line>Diese Seite verwendet einige der „Fugue Icons“ von Yusuke Kamiyamane.</line>
                    <line>
                        <link type="web" href="http://p.yusukekamiyamane.com/">p.yusukekamiyamane.com</link>
                    </line>
                    <line>
                        <link type="web" href="http://pinvoke.com/">pinvoke.com</link>
                    </line>
                </paragraph>
            </section>
        </division>
        <division>
            <heading>Rechtliche Hinweise</heading>
            <section>
                <heading>1. Haftungsbeschränkung</heading>
                <paragraph>Die Inhalte dieser Website werden mit größtmöglicher Sorgfalt erstellt. Der Anbieter übernimmt jedoch keine Gewähr für die
                    Richtigkeit, Vollständigkeit und Aktualität der bereitgestellten Inhalte. Die Nutzung der Inhalte der Website erfolgt auf eigene
                    Gefahr des Nutzers. Namentlich gekennzeichnete Beiträge geben die Meinung des jeweiligen Autors und nicht immer die Meinung des
                    Anbieters wieder. Mit der reinen Nutzung der Website des Anbieters kommt keinerlei Vertragsverhältnis zwischen dem Nutzer und dem
                    Anbieter zustande.</paragraph>
            </section>
            <section>
                <heading>2. Externe Links</heading>
                <paragraph>Diese Website enthält Verknüpfungen zu Websites Dritter ("externe Links"). Diese Websites unterliegen der Haftung der
                    jeweiligen Betreiber. Der Anbieter hat bei der erstmaligen Verknüpfung der externen Links die fremden Inhalte daraufhin überprüft,
                    ob etwaige Rechtsverstöße bestehen. Zu dem Zeitpunkt waren keine Rechtsverstöße ersichtlich. Der Anbieter hat keinerlei Einfluss
                    auf die aktuelle und zukünftige Gestaltung und auf die Inhalte der verknüpften Seiten. Das Setzen von externen Links bedeutet
                    nicht, dass sich der Anbieter die hinter dem Verweis oder Link liegenden Inhalte zu Eigen macht. Eine ständige Kontrolle dieser
                    externen Links ist für den Anbieter ohne konkrete Hinweise auf Rechtsverstöße nicht zumutbar. Bei Kenntnis von Rechtsverstößen
                    werden jedoch derartige externe Links unverzüglich gelöscht.</paragraph>
            </section>
            <section>
                <heading>3. Urheber- und Leistungsschutzrechte</heading>
                <paragraph>Die auf dieser Website veröffentlichten Inhalte unterliegen dem deutschen Urheber- und Leistungsschutzrecht. Jede vom
                    deutschen Urheber- und Leistungsschutzrecht nicht zugelassene Verwertung bedarf der vorherigen schriftlichen Zustimmung des
                    Anbieters oder jeweiligen Rechteinhabers. Dies gilt insbesondere für Vervielfältigung, Bearbeitung, Übersetzung, Einspeicherung,
                    Verarbeitung bzw. Wiedergabe von Inhalten in Datenbanken oder anderen elektronischen Medien und Systemen. Inhalte und Rechte
                    Dritter sind dabei als solche gekennzeichnet. Die unerlaubte Vervielfältigung oder Weitergabe einzelner Inhalte oder kompletter
                    Seiten ist nicht gestattet und strafbar. Lediglich die Herstellung von Kopien und Downloads für den persönlichen, privaten und
                    nicht kommerziellen Gebrauch ist erlaubt.</paragraph>
                <paragraph>Die Darstellung dieser Website in fremden Frames ist nur mit schriftlicher Erlaubnis zulässig.</paragraph>
            </section>
            <section>
                <heading>4. Datenschutz</heading>
                <paragraph>Durch den Besuch der Website des Anbieters können Informationen über den Zugriff (Datum, Uhrzeit, betrachtete Seite)
                    gespeichert werden. Diese Daten gehören nicht zu den personenbezogenen Daten, sondern sind anonymisiert. Sie werden ausschließlich
                    zu statistischen Zwecken ausgewertet. Eine Weitergabe an Dritte, zu kommerziellen oder nichtkommerziellen Zwecken, findet nicht
                    statt.</paragraph>
                <paragraph>Der Anbieter weist ausdrücklich darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail)
                    Sicherheitslücken aufweisen und nicht lückenlos vor dem Zugriff durch Dritte geschützt werden kann.</paragraph>
                <paragraph>Die Verwendung der Kontaktdaten des Impressums zur gewerblichen Werbung ist ausdrücklich nicht erwünscht, es sei denn der
                    Anbieter hatte zuvor seine schriftliche Einwilligung erteilt oder es besteht bereits eine Geschäftsbeziehung. Der Anbieter und
                    alle auf dieser Website genannten Personen widersprechen hiermit jeder kommerziellen Verwendung und Weitergabe ihrer
                    Daten.</paragraph>
            </section>
            <section>
                <heading>5. Besondere Nutzungsbedingungen</heading>
                <paragraph>Soweit besondere Bedingungen für einzelne Nutzungen dieser Website von den vorgenannten Nummern 1. bis 4. abweichen, wird
                    an entsprechender Stelle ausdrücklich darauf hingewiesen. In diesem Falle gelten im jeweiligen Einzelfall die besonderen
                    Nutzungsbedingungen.</paragraph>
            </section>
            <section>
                <paragraph>Quelle: <link type="web" href="http://www.juraforum.de/">www.juraforum.de</link></paragraph>
            </section>
        </division>
    </content>
</page>

=== torstenroeder/tortilla/content/de/kontakt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "../doctypes/page.dtd">

<page>
    <meta-information>
        <title>Kontakt</title>
        <author>Torsten Roeder</author>
        <date>November 2012</date>
        <filename>kontakt.xml</filename>
        <translation lang="en">contact</translation>
    </meta-information>
    <content display="all-divisions">
        <heading>Kontakt</heading>
        <division>
            <paragraph>
                <line>Torsten Roeder</line>
                <link type="web" href="http://www.torstenroeder.de">torstenroeder.de</link>
            </paragraph>
        </division>
    </content>
</page>

=== torstenroeder/tortilla/content/de/entwicklung.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "../doctypes/page.dtd">

<page>
    <meta-information>
        <title>Entwicklung</title>
        <author>Torsten Roeder</author>
        <date>November 2012</date>
        <filename>entwicklung.xml</filename>
        <translation lang="en">development</translation>
    </meta-information>
    <content display="by-divisions" default="first-division">
        <heading>Entwicklung</heading>
        <division name="geschichte">
            <translation lang="en">history</translation>
            <heading>Versionsgeschichte</heading>
            <list type="floating-first-lines">
                <item>
                    <line>Version 1.3</line>
                    <line>translation-Elemente eingebaut</line>
                </item>
                <item>
                    <line>Version 1.2</line>
                    <line>neu strukturiert (Navigation ist jetzt modular)</line>
                </item>
                <item>
                    <line>Version 1.1.2</line>
                    <line>Website-Keywords hinzugefügt</line>
                </item>
                <item>
                    <line>Version 1.1.1</line>
                    <line>ISO-Attribut für Website-Sprache hinzugefügt</line>
                </item>
                <item>
                    <line>Version 1.1</line>
                    <line>alle Überschriften werden als Meta-Keywords abgegriffen</line>
                    <line>image-Element hat jetzt ein class-Attribut</line>
                    <line>language-Element zu den Website-Einstellungen hinzugefügt</line>
                    <line>Konfigurationsstruktur von index.php ist jetzt vollständig</line>
                    <line>alle Links verwenden jetzt vollständige URLs (relative URLs machten Schwierigkeiten beim Crawlen)</line>
                </item>
                <item>
                    <line>Version 1.0.1</line>
                    <line>leicht optimierter Code</line>
                </item>
                <item>
                    <line>Version 1.0</line>
                    <line>erste experimentelle Version</line>
                </item>
            </list>
        </division>
        <division name="geplant">
            <translation lang="en">planned</translation>
            <heading>Geplante Funktionen</heading>
            <list type="floating-first-lines">
                <item>
                    <line>Version 1.3.x</line>
                    <line>logo- und subtitle-Elemente für Website hinzufügen</line>
                    <line>faviconElement für Website hinzufügen</line>
                    <line>allgemeines Update-Datum hinzufügen</line>
                </item>
            </list>
        </division>
    </content>
</page>

=== torstenroeder/tortilla/content/en/examples.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "../doctypes/page.dtd">

<page>
    <meta-information>
        <title>Examples</title>
        <author>Torsten Roeder</author>
        <date>November 2012</date>
        <filename>examples.xml</filename>
        <translation lang="de">beispiele</translation>
    </meta-information>
    <content display="all-divisions">
        <heading>Examples</heading>
        <division>
            <list type="bullets">
                <item>
                    <line>Astrid Kirchhof</line>
                    <line><link type="web" href="http://www.astrid-kirchhof.de">www.astrid-kirchhof.de</link></line>
                </item>
                <item>
                    <line>Karin Schelcher</line>
                    <line><link type="web" href="http://www.karin-schelcher.de">www.karin-schelcher.de</link></line>
                </item>
                <item>
                    <line>Vokalensemble Lankwitz</line>
                    <line><link type="web" href="http://www.vokalensemble-lankwitz.de">www.vokalensemble-lankwitz.de</link></line>
                </item>
                <item>
                    <line>Deutsch-Deutscher Kammerchor e.V.</line>
                    <line><link type="web" href="http://www.deutsch-deutscher-kammerchor.de">www.deutsch-deutscher-kammerchor.de</link></line>
                </item>
            </list>
        </division>
    </content>
</page>

=== torstenroeder/tortilla/content/de/home.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "../doctypes/page.dtd">

<page>
    <meta-information>
        <title>Tortilla</title>
        <author>Torsten Roeder</author>
        <date>November 2012</date>
        <filename>home.xml</filename>
        <translation lang="en">home</translation>
    </meta-information>
    <content display="all-divisions">
        <heading>Was ist das?</heading>
        <division>
            <heading>Einführung</heading>
            <paragraph>Tortilla ist ein einfaches Content Management Framework für kleinere Websites, welches in erster Linie auf XML/XSLT basiert.
                Tortilla nutzt die PHP XML Bibliothek, welche in den meisten Apache-Umgebungen standardmäßig vorhanden ist.</paragraph>
            <paragraph>Tortilla ist auf Inhaltsverwaltung und auf Effizienz ausgerichtet. Im Vergleich zu komplexen, ressourcenintensiven CMS können
                hier alle Aufgaben mit einem Texteditor und einem FTP-Zugang erledigt werden.</paragraph>
            <paragraph>Die Verwendung von Tortilla ist vergleichbar mit dem Bearbeiten einer HTML-Seite. Der wichtigste Unterschied ist, dass Tortilla
                eine inhaltsorientierte Struktur bereitstellt, welche später automatisch nach HTML transformiert wird.</paragraph>
            <paragraph>Tortilla verlangt, dass eine vorhandene Dokumentstruktur verwendet wird. Die grundlegende Element ist eine Seite, welche
                hierarchisch in Abschnitte und Sektionen gegliedert ist. Inhaltselemente wie Links und Listen entsprechen mehr oder weniger den
                typischen HTML-Elementen. Die Struktur erlaubt es außerdem, Inhalte mit CSS-Klassen zu verknüpfen.</paragraph>
        </division>
    </content>
</page>

=== torstenroeder/tortilla/content/en/contact.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "../doctypes/page.dtd">

<page>
    <meta-information>
        <title>Contact</title>
        <author>Torsten Roeder</author>
        <date>November 2012</date>
        <filename>contact.xml</filename>
        <translation lang="de">kontakt</translation>
    </meta-information>
    <content display="all-divisions">
        <heading>Contact</heading>
        <division>
            <paragraph>
                <line>Torsten Roeder</line>
                <link type="web" href="http://www.torstenroeder.de">torstenroeder.de</link>
            </paragraph>
        </division>
    </content>
</page>

=== torstenroeder/tortilla/content/en/development.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "../doctypes/page.dtd">

<page>
    <meta-information>
        <title>Development</title>
        <author>Torsten Roeder</author>
        <date>November 2012</date>
        <filename>development.xml</filename>
        <translation lang="de">entwicklung</translation>
    </meta-information>
    <content display="by-divisions" default="first-division">
        <heading>Development</heading>
        <division name="history">
            <translation lang="de">geschichte</translation>
            <heading>Version History</heading>
            <list type="floating-first-lines">
                <item>
                    <line>version 1.3</line>
                    <line>translation elements included</line>
                </item>
                <item>
                    <line>version 1.2</line>
                    <line>restructured (navigation is now modular)</line>
                </item>
                <item>
                    <line>version 1.1.2</line>
                    <line>added optional site keywords</line>
                </item>
                <item>
                    <line>version 1.1.1</line>
                    <line>added site language iso attribute</line>
                </item>
                <item>
                    <line>version 1.1</line>
                    <line>grab all headings as meta keywords</line>
                    <line>added class attribute to image element</line>
                    <line>added site language element</line>
                    <line>configuration structure of index.php is now complete</line>
                    <line>all links now operate with complete urls (relative urls caused crawling trouble)</line>
                </item>
                <item>
                    <line>version 1.0.1</line>
                    <line>slightly optimized code</line>
                </item>
                <item>
                    <line>version 1.0</line>
                    <line>first experimental version</line>
                </item>
            </list>
        </division>
        <division name="planned">
            <translation lang="de">geplant</translation>
            <heading>Planned Features</heading>
            <list type="floating-first-lines">
                <item>
                    <line>version 1.3.x</line>
                    <line>add optional site logo and subtitle elements</line>
                    <line>add optional site favicon element</line>
                    <line>add general site update date</line>
                </item>
            </list>
        </division>
    </content>
</page>

=== torstenroeder/tortilla/content/de/was-ist-das.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "../doctypes/page.dtd">

<page>
    <meta-information>
        <title>Was ist das?</title>
        <author>Torsten Roeder</author>
        <date>November 2012</date>
        <filename>was-ist-das.xml</filename>
        <translation lang="en">what-is-this</translation>
    </meta-information>
    <content display="all-divisions">
        <heading>Was ist das?</heading>
        <division name="einfuehrung">
            <translation lang="en">introduction</translation>
            <heading>Introduction</heading>
            <paragraph>Tortilla is a simple content management framework for personal websites which operates mainly on XML/XSLT. Tortilla uses the
                PHP XML library, which is included in most Apache environments by standard.</paragraph>
            <paragraph>Tortilla focuses on content, but in comparison to a complex and resource intense CMS, all tasks can be done with a text editor
                and ftp access.</paragraph>
            <paragraph>Using Tortilla is similar to editing a page in HTML. The main difference is that Tortilla provides a content oriented structure
                which is then automatically rendered to HTML.</paragraph>
            <paragraph>Tortilla requires you to use its predefined document structure. The basic unit is a page, which is then hierarchically
                subdivided into divisions and sections. Content elements like links and lists correspond more or less to typical HTML elements. The
                structure also allows to associate content elements with custom CSS classes.</paragraph>
        </division>
    </content>
</page>
