=== torstenroeder/tortilla/content/doctypes/page.dtd
<!-- TORTILLA PAGE DTD -->
<!-- version 1.3 -->

<!ELEMENT page (meta-information,content) >

    <!ELEMENT meta-information (title,author*,date,filename,translation?) >

        <!ELEMENT title       (#PCDATA) >
        <!ELEMENT author      (#PCDATA) >
        <!ELEMENT date        (#PCDATA) >
        <!ELEMENT filename    (#PCDATA) >
        <!ELEMENT translation (#PCDATA) >
        <!ATTLIST translation
            lang  (de|en)  "de"
        >

    <!ELEMENT content
        (heading|image|division
        |list|paragraph|line|get-content)*
    >
    <!ATTLIST content
        display  (all-divisions|by-divisions|selected-image)  "all-divisions"
        default  (first-division|division-list)               "first-division"
        objects  (image)                                      #IMPLIED
        class    CDATA                                        #IMPLIED
    >

        <!ELEMENT heading (#PCDATA) >
        <!ATTLIST heading
            class  CDATA  #IMPLIED
            short  CDATA  #IMPLIED
        >
        
        <!ELEMENT division
            (translation?,(heading|image|video|map|section|list|paragraph|line|get-content)*)
        >
        <!ATTLIST division
            name   CDATA  #IMPLIED
            class  CDATA  #IMPLIED
        >
        
        <!ELEMENT section
            (heading|image|video|map
            |list|paragraph|line|get-content)*
        >
        <!ATTLIST section
            name   CDATA  #IMPLIED
            class  CDATA  #IMPLIED
        >
        
        <!-- PARAGRAPHS -->

        <!ELEMENT paragraph
            (#PCDATA
            |heading|image|line|list
            |link|get-content)*
        >
        <!ATTLIST paragraph
            content  (image)  #IMPLIED
        >
        
            <!-- LINES -->

            <!ELEMENT line (#PCDATA|link)* >
            <!ATTLIST line
                content  CDATA  "text"
            >

            <!-- LINKS -->

            <!ELEMENT link (#PCDATA)* >
            <!ATTLIST link
                type  (email|site|web|file|openstreetmap)  #REQUIRED
                href       CDATA  #IMPLIED
                latitude   CDATA  #IMPLIED
                longitude  CDATA  #IMPLIED
                zoom       CDATA  #IMPLIED
            >

        <!-- LISTS -->

        <!ELEMENT list (item|get-content)* >
        <!ATTLIST list
            type  (bullets|floating-first-lines|paragraphs)  #IMPLIED
            content (keywords) #IMPLIED
        >
        
            <!ELEMENT item
                (#PCDATA
                |heading|image|line)* 
            >

        <!-- IMAGES, VIDEOS, MAPS -->

        <!ELEMENT image (#PCDATA) >
        <!ATTLIST image
            filename   CDATA  #REQUIRED
            extension  CDATA  #REQUIRED
            float    (left|right|none)  #IMPLIED
            border   (default|none)  #IMPLIED
        >

        <!ELEMENT video (#PCDATA) >
        <!ATTLIST video
            title       CDATA  #REQUIRED
            width       CDATA  #REQUIRED
            height      CDATA  #REQUIRED
            margin      CDATA  #REQUIRED
            filename    CDATA  #REQUIRED
            startimage  CDATA  #REQUIRED
        >

        <!ELEMENT map (#PCDATA) >
        <!ATTLIST map
            type        (openstreetmap)  #REQUIRED
            latitude    CDATA  #REQUIRED
            longitude   CDATA  #REQUIRED
            zoom        CDATA  #REQUIRED
            filename    CDATA  #REQUIRED
        >

        <!-- EXTERNAL CONTENT -->

        <!ELEMENT get-content EMPTY>
        <!ATTLIST get-content
            from       CDATA  #REQUIRED
            container  CDATA  #REQUIRED
            element    CDATA  #REQUIRED
            position   CDATA  #IMPLIED
        >

=== torstenroeder/tortilla/content/en/download.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "../doctypes/page.dtd">

<page>
    <meta-information>
        <title>Download</title>
        <author>Torsten Roeder</author>
        <date>November 2012</date>
        <filename>download.xml</filename>
        <translation lang="de">download</translation>
    </meta-information>
    <content display="all-divisions">
        <heading>Download</heading>
        <division>
            <paragraph>
                <line>Version 1.3</line>
                <line><link type="file">tortilla_1-3.zip</link></line>
            </paragraph>
        </division>
    </content>
</page>

=== torstenroeder/tortilla/content/en/documentation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "../doctypes/page.dtd">

<page>
    <meta-information>
        <title>Documentation</title>
        <author>Torsten Roeder</author>
        <date>November 2012</date>
        <filename>documentation.xml</filename>
        <translation lang="de">dokumentation</translation>
    </meta-information>
    <content display="by-divisions" default="first-division">
        <heading>Documentation</heading>
        <division name="files">
            <translation lang="de">konfiguration</translation>
            <heading>Configuration</heading>
            <paragraph>There are three files where configurations can be edited:</paragraph>
            <list type="floating-first-lines">
                <item>
                    <line>index.php</line>
                    <line>here you need to insert your server names (multiple servers allowed) and the default page</line>
                </item>
                <item>
                    <line>site.xml</line>
                    <line>this file is language specific (see subfolders of content/) and determines the general site structure</line>
                </item>
                <item>
                    <line>.htaccess</line>
                    <line>if you need some special filetypes to be forwarded to the browser, insert them here</line>
                </item>
            </list>
        </division>
    </content>
</page>

=== torstenroeder/tortilla/content/de/dokumentation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page SYSTEM "../doctypes/page.dtd">

<page>
    <meta-information>
        <title>Dokumentation</title>
        <author>Torsten Roeder</author>
        <date>November 2012</date>
        <filename>dokumentation.xml</filename>
        <translation lang="en">documentation</translation>
    </meta-information>
    <content display="by-divisions" default="first-division">
        <heading>Dokumentation</heading>
        <division name="files">
            <translation lang="en">configuration</translation>
            <heading>Konfiguration</heading>
            <paragraph>Es gibt drei Dateien, in denen Konfigurationen bearbeitet werden können:</paragraph>
            <list type="floating-first-lines">
                <item>
                    <line>index.php</line>
                    <line>hier müssen die Servernamen eingesetzt werden (es sind mehrere erlaubt) sowie die Startseite</line>
                </item>
                <item>
                    <line>site.xml</line>
                    <line>diese Datei ist sprachspezifisch (siehe Unterordnet von content/) und bestimmt die grundlegende Seitenstruktur</line>
                </item>
                <item>
                    <line>.htaccess</line>
                    <line>sofern besondere Dateiformate an den Browser weitergegeben werden sollen, können diese hier vermerkt werden</line>
                </item>
            </list>
        </division>
    </content>
</page>
