=== torstenroeder/tortilla/content/doctypes/site.dtd
<!-- TORTILLA SITE DTD -->
<!-- version 1.3 -->

<!ELEMENT site (title,subtitle?,language,keywords?,navigation) >

    <!ELEMENT title (#PCDATA) >
    <!ELEMENT subtitle (#PCDATA) >
    <!ELEMENT language (#PCDATA) >
    <!ATTLIST language
        iso  CDATA  #REQUIRED
    >
    <!ELEMENT keywords (#PCDATA) >

    <!ELEMENT navigation (item)* >
    <!ATTLIST navigation
        type  (cascading|parallel)  #IMPLIED
    >
        
    <!ELEMENT item (#PCDATA) >
    <!ATTLIST item
        name  CDATA  #IMPLIED
    >

=== torstenroeder/tortilla/content/de/site.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE site SYSTEM "../doctypes/site.dtd">

<site>
    
    <!-- setzt <h1> auf allen Seiten -->
    <title>Tortilla</title>
    
    <!-- Meta-Informationen -->
    <language iso="de">Deutsch</language>
    <keywords>Tortilla, Content Management, Framework, XML, XSLT, PHP, DTD</keywords>
    
    <!-- Hauptnavigation -->
    <navigation type="parallel">
        <item name="home">Was ist das?</item>
        <item name="beispiele">Beispiele</item>
        <item name="download">Download</item>
        <item name="entwicklung">Entwicklung</item>
        <item name="dokumentation">Dokumentation</item>
    </navigation>
    
</site>

=== torstenroeder/tortilla/content/en/site.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE site SYSTEM "../doctypes/site.dtd">

<site>
    
    <!-- set <h1> for all pages -->
    <title>Tortilla</title>
    
    <!-- meta information -->
    <language iso="en">English</language> <!-- meta information -->
    <keywords>Tortilla, Content Management, Framework, XML, XSLT, PHP, DTD</keywords>
    
    <!-- primary navigation -->
    <navigation type="parallel">
        <item name="home">What is this?</item>
        <item name="examples">Examples</item>
        <item name="download">Download</item>
        <item name="development">Development</item>
        <item name="documentation">Documentation</item>
    </navigation>
    
</site>
